DROP TABLE STORE_REVIEW;
DROP TABLE STORE_QUESTION;
DROP TABLE STORE_CATEGORY;
DROP TABLE CATEGORY;
DROP TABLE STORE;
DROP TABLE STORE_STATUS;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MEM_NO	NUMBER	NOT NULL PRIMARY KEY,
	ID	VARCHAR2(20)	NOT NULL,
    PWD	VARCHAR2(20)	NOT NULL,
	NICKNAME	VARCHAR2(20)	NOT NULL,
	NAME	VARCHAR2(20)	NOT NULL,
	EMAIL	VARCHAR2(20)	NOT NULL,
    PHONE	VARCHAR2(13)	NOT NULL,
	LOCATION	VARCHAR2(30)	NULL,
	BIRTH	DATE	NULL,
    ENROLL_DATE	DATE	DEFAULT SYSDATE NOT NULL,
	STATUS_YN	CHAR(1)	DEFAULT 'N'	NOT NULL,
    GRADE	CHAR(1)	DEFAULT 'V' NOT NULL,
	B_BTI	VARCHAR2(15) DEFAULT 0 NULL,
	B_MATE_YN	CHAR(1)	DEFAULT 'N'	NULL
);

CREATE TABLE STORE_STATUS(
   STORE_NO NUMBER PRIMARY KEY,
   MANAGER NUMBER REFERENCES MEMBER(MEM_NO) NULL,
   STATUS NUMBER DEFAULT 1 NULL CHECK(STATUS IN(0, 1, 2, 3))
);

CREATE TABLE STORE (
	STORE_NO	NUMBER REFERENCES STORE_STATUS(STORE_NO) NOT NULL PRIMARY KEY,
    NAME	VARCHAR2(40)	NOT NULL,
	LOCAL	VARCHAR2(10)	NOT NULL,
	ADDRESS	VARCHAR2(200)	NOT NULL,
	OPEN	VARCHAR2(100)	NULL,
	CLOSE	VARCHAR2(100)	NULL,
	BREAKTIME	VARCHAR2(100)	NULL,
	DAYOFF	VARCHAR2(100)	NULL,
	TEL	NUMBER	NULL,
	PARKING	VARCHAR2(8)	NULL,
	INSTA	VARCHAR2(200)	NULL,
	YOUTUBE	VARCHAR2(100)	NULL,
	LOGO	VARCHAR2(100)	NULL
);

CREATE TABLE CATEGORY(
    CATE_NO NUMBER PRIMARY KEY,
    CATE VARCHAR2(100)
);

CREATE TABLE STORE_CATEGORY(
    STORE_NO NUMBER REFERENCES STORE(STORE_NO),
    CATE_NO NUMBER  REFERENCES CATEGORY(CATE_NO),
    PRIMARY KEY (STORE_NO, CATE_NO)
);

CREATE TABLE STORE_QUESTION (
	SQ_NO	NUMBER	NOT NULL PRIMARY KEY,
	STORE_NO	NUMBER	NOT NULL REFERENCES STORE(STORE_NO),
	MEM_NO	NUMBER	NOT NULL REFERENCES MEMBER(MEM_NO),
	QUESTION	VARCHAR2(1000)	NOT NULL,
	QUESTION_DATE	DATE	NOT NULL,
	ANSWER	VARCHAR2(1000)	NULL,
	ANSWER_DATE	DATE	NULL
);

CREATE TABLE STORE_REVIEW (
	SR_NO	NUMBER	NOT NULL PRIMARY KEY,
	STORE_NO	NUMBER	NOT NULL REFERENCES STORE(STORE_NO),
	MEM_NO	NUMBER	NOT NULL REFERENCES MEMBER(MEM_NO),
	REVIEW	VARCHAR2(1000)	NOT NULL,
	REVIEW_DATE	DATE	NOT NULL,
    STAR NUMBER NOT NULL,
	ANSWER	VARCHAR2(1000)	NULL,
	ANSWER_DATE	DATE	NULL
);

DROP SEQUENCE SEQ_MEM_NO;
DROP SEQUENCE SEQ_STORE;
DROP SEQUENCE SEQ_CATE_NO;
DROP SEQUENCE SEQ_SQ_NO;
DROP SEQUENCE SEQ_SR_NO;

CREATE SEQUENCE SEQ_MEM_NO
NOCACHE;

CREATE SEQUENCE SEQ_STORE_NO
NOCACHE;

CREATE SEQUENCE SEQ_CATE_NO
NOCACHE;

CREATE SEQUENCE SEQ_SQ_NO
NOCACHE;

CREATE SEQUENCE SEQ_SR_NO
NOCACHE;

INSERT INTO CATEGORY VALUES(1, '무선인터넷');
INSERT INTO CATEGORY VALUES(2, '드라이브스루');
INSERT INTO CATEGORY VALUES(3, '비건');
INSERT INTO CATEGORY VALUES(4, '24시');
INSERT INTO CATEGORY VALUES(5, '놀이방');
INSERT INTO CATEGORY VALUES(6, '테라스');
INSERT INTO CATEGORY VALUES(7, '반려동물');
INSERT INTO CATEGORY VALUES(8, '전화예약');

INSERT INTO MEMBER VALUES(1, 'ADMIN', 'ADMIN', '관리자', 'JTY', 'JTY@', '010', '서울시', SYSDATE, SYSDATE, DEFAULT, DEFAULT, '크림빵', DEFAULT);
INSERT INTO STORE_STATUS VALUES(1, 1, 0); -- 숫자로 멤버 받아오기
INSERT INTO STORE VALUES(1, '스타벅스', '경기도', '화성시', '10', '18', '12-13', '일요일', '010', '주차', 'INSTA', 'YOUTUBE', 'LOGO');
INSERT INTO STORE_CATEGORY VALUES(1, 1);
INSERT INTO STORE_CATEGORY VALUES(1, 2);
INSERT INTO STORE_CATEGORY VALUES(1, 8);
INSERT INTO STORE_QUESTION VALUES(1, 1, 1, '안농하세요', SYSDATE, '넵', SYSDATE);
INSERT INTO STORE_REVIEW VALUES(1, 1, 1, '아주좋아용', SYSDATE, 3.5, '넵', SYSDATE);

COMMIT;

UPDATE CATEGORY SET CATE = '이노넷' WHERE CATE_NO = 1;

COMMIT;